server:
  port: 8080
spring:
  application:
    name: "productos"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: jdbc:postgresql://localhost:5432/producto_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
