server:
  port: 8080

spring:
  application:
    name: "productos"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/productos_db"
    username: root
    password: root
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8083, http://localhost:8080"
