spring:
  application:
    name: "productos"
  devtools:
    add-properties: false
  profiles:
    include: null

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productos_db
    username: root
    password: root

adapters:
   r2dbc:
     host: localhost
     port: 5432
     database: productos_db
     schema: public
     username: root
     password: root

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG


cors:
  allowed-origins: "http://localhost:4200,http://localhost:8083,http://localhost:8080,http://localhost:5173"