spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/producto/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**

  application:
    name: gateway
server:
  port: 8111