services:
  postgresql:
    container_name: ecommerce_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservicios-ecommerce-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - microservicios-ecommerce-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - microservicios-ecommerce-net
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeper_ecommerce
    environment:
      #just for local
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - microservicios-ecommerce-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_ms_uptc
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservicios-ecommerce-net

  mail-dev:
    container_name: mail-dev-ecommerce
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025




  zipkin:
    container_name: zipkin_ecommerce
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservicios-ecommerce-net

networks:
  microservicios-ecommerce-net:
    driver: bridge

volumes:
  postgres:
  mongodb:
