server:
  port: 8088
spring:
  application:
    name: customer-service
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/test?authSource=admin"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080 /http://localhost:8888"
